# Changes here will be overwritten by Copier
_commit: a15dbc3
_src_path: gh:bartlomiej-aleksiejczyk/django-template-copier
choosen_databse: sqlite
is_huey_enabled: false
project_name: filesystem-based-information-system
