#TODO: Investigate long stopping/killing time of django container
services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: >
      sh -c "python wait_for_db.py &&
            python manage.py makemigrations --noinput &&
            python manage.py migrate --noinput &&
            python manage.py createinitialsuperuser &&
            python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      DJANGO_TIME_ZONE: Europe/Warsaw
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SETTINGS_MODULE: "core.settings"
      DJANGO_SECRET_KEY: "your-secret-key-here"
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost,192.168.0.29,0.0.0.0,127.0.0.1,[::1]"
      PAGES_BASE_DIR: "information_system/"

    volumes:
      - .:/app
      - sqlite_data:/db
      - nfs_data:/app/information_system

  resilient_worker:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    depends_on:
      - django
    command: >
      bash -c "while true; do
                 python manage.py watch_files_for_change;
                 sleep 3600;
               done"
    volumes:
      - .:/app
      - sqlite_data:/db
      - nfs_data:/app/information_system

volumes:
  sqlite_data:
  nfs_data:
    driver_opts:
      type: "nfs"
      o: "addr=${NFS_SHARE_IP},rw"
      device: ":${NFS_SHARE_PATH}"
